apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: thanak81-api-tester-plz1
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/LynaSovann/thanak81-api-tester-plz1.git
    targetRevision: main
    path: manifests
  destination:
    server: https://kubernetes.default.svc
    namespace: thanak81-api-tester-plz1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
  revisionHistoryLimit: 5
